// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuaA2bXrfqZahRY0QMVY2D2eSncLd1rWk',
    appId: '1:1081233116677:web:8fe265e12186d4ea02166c',
    messagingSenderId: '1081233116677',
    projectId: 'chat-66e5b',
    authDomain: 'chat-66e5b.firebaseapp.com',
    storageBucket: 'chat-66e5b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCM9ADN5Qtn5bEQJmUT6_06cJb73y6Di04',
    appId: '1:1081233116677:android:2ec97a5db7685ffb02166c',
    messagingSenderId: '1081233116677',
    projectId: 'chat-66e5b',
    storageBucket: 'chat-66e5b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSvvWnRdqBq33VT9sHQALK8HbOW4YkWEI',
    appId: '1:1081233116677:ios:c98c90960802f37702166c',
    messagingSenderId: '1081233116677',
    projectId: 'chat-66e5b',
    storageBucket: 'chat-66e5b.appspot.com',
    iosBundleId: 'com.example.chatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSvvWnRdqBq33VT9sHQALK8HbOW4YkWEI',
    appId: '1:1081233116677:ios:62acbed5f5eb8e6802166c',
    messagingSenderId: '1081233116677',
    projectId: 'chat-66e5b',
    storageBucket: 'chat-66e5b.appspot.com',
    iosBundleId: 'com.example.chatApplication.RunnerTests',
  );
}
